# states.py
CHOIX_LANGUE, ADRESSE_PORTEFEUILLE, RESEAU_BLOCKCHAIN, MONTANT_DEPOT, MONTANT_DEPOT_SUPPLEMENTAIRE, SAISIE_HASH_RETRAIT,SAISIE_HASH_RETRAIT2, ADRESSE_PARRAINAGE,RESEAU_PARRAINAGE = range(9)
