'''
Author: pegazus-alpha pourdebutantp@gmail.com
Date: 2025-06-13 08:16:44
LastEditors: pegazus-alpha pourdebutantp@gmail.com
LastEditTime: 2025-07-19 02:24:47
FilePath: \telegram_bot\etats.py
Description: 这是默认设置,请设置`customMade`, 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
'''
# # states.py
# CHOIX_LANGUE, ADRESSE_PORTEFEUILLE, RESEAU_BLOCKCHAIN, MONTANT_DEPOT, MONTANT_DEPOT_SUPPLEMENTAIRE, SAISIE_HASH_RETRAIT,SAISIE_HASH_RETRAIT2, ADRESSE_PARRAINAGE,RESEAU_PARRAINAGE,HASH_TRANSACTION_DEPOT,MODE_PAIEMENT,CHOIX_PAYS,CHOIX_OPERATEUR,NUMERO_MOBILE,NOM_UTILISATEUR,SAISIE_IMAGE_PAIEMENT_LOCAL,MODE_PAIEMENT2,CHOIX_PAYS2,CHOIX_OPERATEUR2,NUMERO_MOBILE2,NOM_UTILISATEUR2,SAISIE_IMAGE_PAIEMENT_LOCAL2 = range(22)
CHOIX_LANGUE, ADRESSE_PORTEFEUILLE, RESEAU_BLOCKCHAIN, MONTANT_DEPOT, MONTANT_DEPOT_SUPPLEMENTAIRE, HASH_TRANSACTION_DEPOT_SUPPLEMENTAIRE, SAISIE_HASH_RETRAIT, SAISIE_HASH_RETRAIT2, ADRESSE_PARRAINAGE, RESEAU_PARRAINAGE, HASH_TRANSACTION_DEPOT, MODE_PAIEMENT, CHOIX_PAYS, CHOIX_OPERATEUR, NUMERO_MOBILE, NOM_UTILISATEUR, SAISIE_IMAGE_PAIEMENT_LOCAL, MODE_PAIEMENT2, CHOIX_PAYS2, CHOIX_OPERATEUR2, NUMERO_MOBILE2, NOM_UTILISATEUR2, SAISIE_IMAGE_PAIEMENT_LOCAL2 = range(24)