

# # states.py
CHOIX_LANGUE, ADRESSE_PORTEFEUILLE, RESEAU_BLOCKCHAIN, MONTANT_DEPOT, MONTANT_DEPOT_SUPPLEMENTAIRE, SAISIE_HASH_RETRAIT,SAISIE_HASH_RETRAIT2, ADRESSE_PARRAINAGE,RESEAU_PARRAINAGE,MODE_PAIEMENT,CHOIX_PAYS,CHOIX_OPERATEUR,NUMERO_MOBILE,NOM_UTILISATEUR,SAISIE_IMAGE_PAIEMENT_LOCAL,MODE_PAIEMENT2,CHOIX_PAYS2,CHOIX_OPERATEUR2,NUMERO_MOBILE2,NOM_UTILISATEUR2,SAISIE_IMAGE_PAIEMENT_LOCAL2 = range(21)
# CHOIX_LANGUE, ADRESSE_PORTEFEUILLE, RESEAU_BLOCKCHAIN, MONTANT_DEPOT, MONTANT_DEPOT_SUPPLEMENTAIRE, HASH_TRANSACTION_DEPOT_SUPPLEMENTAIRE, SAISIE_HASH_RETRAIT, SAISIE_HASH_RETRAIT2, ADRESSE_PARRAINAGE, RESEAU_PARRAINAGE, HASH_TRANSACTION_DEPOT, MODE_PAIEMENT, CHOIX_PAYS, CHOIX_OPERATEUR, NUMERO_MOBILE, NOM_UTILISATEUR, SAISIE_IMAGE_PAIEMENT_LOCAL, MODE_PAIEMENT2, CHOIX_PAYS2, CHOIX_OPERATEUR2, NUMERO_MOBILE2, NOM_UTILISATEUR2, SAISIE_IMAGE_PAIEMENT_LOCAL2 = range(24)
RETRAIT_EN_ATTENTE={}
HASH_TRANSACTION_DEPOT = ""